### ISSUE TITLE
Project fails to build immediately after generation

### ISSUE THREAD

**Issue by kd8azz** [bazelbuild/e4b#12]
Hello,

I have created a new project via Other > Import Bazel Workspace.  The output in the console then indicates failure.

The output is rather confusing to me, so I've pasted it ~verbatim, along with the BUILD file it references.

BUILD file in question ("/home/user/Source/Project/src/main/path/to/code/BUILD")

```
package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

java_proto_library(
  name = "myproto",
  protos = ["myproto.proto"],
)

java_library(
  name = "code",
  srcs = glob(
    ["*.java"],
    exclude = ["Main.java", "Other.java"]),
  deps = [
    ":myproto",
    ":myproto_compile_imports",
    "//external:com/google/auto/value",
    "//external:com/google/guava",
    "//external:org/objenesis",
    "//external:net/bytebuddy",
    "//src/main/path/component",
    "//src/main/path:another",
  ],
  javacopts = ["-parameters"],
)

java_binary(
  name = "main",
  srcs = ["Main.java", "Other.java"],
  deps = [
    ":code",
    ":myproto",
    ":myproto_compile_imports",
    "//external:com/google/guava",
    "//external:org/ow2/asm",
    "//external:org/objenesis",
    "//external:net/bytebuddy",
    "//src/main/path/component",
  ],
  main_class = "path.to.code.Main",
)
```

Tool output

```
*** Running [/usr/local/bin/bazel, --watchfs, build, --package_path, %workspace%:/home/user/Source/Open/github.com/google/bazel/base_workspace:/home/user/bin/eclipse-install/java-mars2/eclipse/plugins/com.google.devtools.bazel.e4b_0.0.1/resources, --experimental_interleave_loading_and_analysis, --strategy=Javac=worker, --noexperimental_check_output_files, --aspects=tools/must/be/unique/e4b_aspect.bzl%e4b_aspect, -k, --output_groups=ide-info-text,ide-resolve,-_,-defaults, --experimental_show_artifacts, //src/test/path/..., //src/main/path/...] from /home/user/Source/Project ***
WARNING: Option 'experimental_interleave_loading_and_analysis' is deprecated.
____Loading...
WARNING: /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/external/com_github_google_protobuf/protobuf.bzl:90:19: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
ERROR: /home/user/Source/Project/src/main/path/to/code/BUILD:5:1: in //tools/must/be/unique:e4b_aspect.bzl%e4b_aspect aspect on proto_language_deps rule //src/main/path/to/code:myproto_compile_deps: 
Traceback (most recent call last):
    File "/home/user/Source/Project/src/main/path/to/code/BUILD", line 5
        //tools/must/be/unique:e4b_aspect.bzl%e4b_aspect(...)
    File "/home/user/bin/eclipse-install/java-mars2/eclipse/plugins/com.google.devtools.bazel.e4b_0.0.1/resources/tools/must/be/unique/e4b_aspect.bzl", line 95, in _aspect_impl
        for dep in deps: ...
type 'bool' is not iterable.
WARNING: /home/user/.cache/bazel/_bazel_user/00bb1210de2173919b75bf7db0a13118/external/com_github_google_protobuf/protobuf.bzl:96:28: Variables HOST_CFG and DATA_CFG are deprecated in favor of strings "host" and "data" correspondingly.
____Found 18 targets...
____[0 / 1] BazelWorkspaceStatusAction stable-status.txt
Build artifacts:
ERROR: command succeeded, but not all targets were analyzed.
____Elapsed time: 0.114s, Critical Path: 0.00s
```

**Comment by kd8azz** [comment]
Just as I posted this bug, I got more output in my terminal.  It seems that the build finally went through, after several minutes.  I'm not sure what's going on, here.

**Comment by kd8azz** [comment]
Hasn't built since; (I had to delete and recreate it) and the class path hasn't been generated.

**Comment by damienmg** [comment]
The aspect for some reason gets applied to [proto_language_deps](https://github.com/pubref/rules_protobuf/blob/master/protobuf/internal/proto_language.bzl#L109). We should filter it out.

**Comment by damienmg** [comment]
Ok seeing the code of the aspect, it is obvious why it fails: https://github.com/bazelbuild/e4b/blob/master/com.google.devtools.bazel.e4b/resources/tools/must/be/unique/e4b_aspect.bzl#L92 applies to all the rules

**Comment by damienmg** [comment]
I'll make a new release now.

**Comment by kd8azz** [comment]
Thank you; that problem is now fixed.
