### ISSUE TITLE
Plugin doesn't work against recent Bazel version

### ISSUE THREAD

**Issue by davido** [bazelbuild/e4b#55]
Trying to follow the instructions and set up Eclipse project on Bazel master is failing with:

```
ERROR: /home/davido/projects/bazel/src/test/java/com/google/devtools/build/android/desugar/BUILD:696:1: in //tools/must/be/unique:e4b_aspect.bzl%e4b_aspect aspect on java_library rule //src/test/java/com/google/devtools/build/android/desugar:testdata_like_in_android_studio: 
Traceback (most recent call last):
	File "/home/davido/projects/bazel/src/test/java/com/google/devtools/build/android/desugar/BUILD", line 696
		//tools/must/be/unique:e4b_aspect.bzl%e4b_aspect(...)
	File "/home/davido/pgm/eclipse-oxygen/eclipse/plugins/com.google.devtools.bazel.e4b_0.0.2/resources/tools/must/be/unique/e4b_aspect.bzl", line 97, in _aspect_impl
		dep.intellij_info_files
object of type 'Target' has no field 'intellij_info_files'.
ERROR: Analysis of aspect '/tools/must/be/unique/e4b_aspect%e4b_aspect of //src/test/java/com/google/devtools/build/android/desugar:testdata_like_in_android_studio' failed; build aborted.
____Elapsed time: 1.688s
```

Bazel is on: bf96c50e0c9afd3da8d937948c3636f09a0e80d7

Side not: It is not clear how to compile this Eclipse plugin from master.
I tried with "bazel build //...", but this command was looping over downloading different bazel versions (?) and I cancelled it.

**Comment by davido** [comment]
Looks like uncommenting these lines: ~/pgm/eclipse-oxygen/eclipse/plugins/com.google.devtools.bazel.e4b_0.0.2/resources/tools/must/be/unique/e4b_aspect.bzl fixed the first breakage:

```python
  for attr_name in DEPENDENCY_ATTRIBUTES:
    if hasattr(rule_attrs, attr_name):
      deps = getattr(rule_attrs, attr_name)
      if type(deps) == 'list':
#        for dep in deps:
#          ide_info_text = ide_info_text | dep.intellij_info_files.ide_info_text
#          ide_resolve_files = ide_resolve_files | dep.intellij_info_files.ide_resolve_files
        all_deps += [str(dep.label) for dep in deps]
```

**Comment by davido** [comment]
Well, now it's failing in android rules. I don't use android:

```
ERROR: /home/davido/.cache/bazel/_bazel_davido/0fa756dec521553dbe2dde6b6eac99b4/external/bazel_tools/tools/android/BUILD:267:1: Executing genrule @bazel_tools//tools/android:no_android_sdk_repository_error failed (Exit 1).
This build requires an Android SDK. Please add the android_sdk_repository rule to your WORKSPACE.
____Elapsed time: 222.555s, Critical Path: 30.76s
```

**Comment by damienmg** [comment]
Arf this is fixed at head. I need to cut a new release for the plugin.

**Comment by markuskobler** [comment]
Anything stopping a new release?

**Comment by hridder** [comment]
(*thump*) (*thump*) Is this thing on? 😅 

Using bazel 0.8.0 fails with:
```
ERROR: /private/var/tmp/_bazel_censored/d524661b555353cf611f531fca4c7d0f/external/com_google_appengine_remote_api/BUILD:13:1: in //tools/must/be/unique:e4b_aspect.bzl%e4b_aspect aspect on java_import rule @com_google_appengine_remote_api//:link: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_censored/d524661b555353cf611f531fca4c7d0f/external/com_google_appengine_remote_api/BUILD", line 13
		//tools/must/be/unique:e4b_aspect.bzl%e4b_aspect(...)
	File "/Applications/Eclipse.app/Contents/Eclipse/plugins/com.google.devtools.bazel.e4b_0.0.2/resources/tools/must/be/unique/e4b_aspect.bzl", line 88, in _aspect_impl
		set()
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
```
This appears to be fixed 9 months ago in #51 / 94c6f4a96b6b0e28e42abff037d97a29880c37c9

What's stopping a new release? Has anyone successfully built the plugin locally and can give hints?

**Comment by damienmg** [comment]
I am using it at head. I will do a new release on Monday.

**Comment by damienmg** [comment]
Closing this bug in favor of #57.
